name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
       