
  deploy:
    name: Deploy
    # The os to run the job on
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          publish_dir: ./build
