name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
  

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
        env:
            CI: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: .next # The folder the action should deploy.
          CLEAN: true 